version: "2"
services:
  redis:
    image: redis
  mysql:
    hostname: localhost
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
  web:
    build: .
    ports:
      - "8100:8100"
    volumes:
      - .:/web
    links:
      - redis
      - mysql
    command:
        python app.py
  init:
    build: .
    volumes:
      - .:/web
    links:
      - redis
      - mysql
    command:
      - /bin/sh
      - -c
      - |
        export FLASK_APP=manager.py
        flask initdb
  celery:
    build: .
    volumes:
      - .:/web
    links:
      - redis
      - mysql
    command: celery -A wechat worker -l info -B
